import type { Metadata } from 'next';

import '../styles/main.scss';

export const metadata: Metadata = {
  title: 'StatsBomb',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
